"""
Loop self-checks.

The one property this whole scene is built around: **frame N+1 is frame 1**.
Every animated value is generated by a phase, and the phase must arrive back at
its starting value exactly one step past the last rendered frame — not close to
it, exactly at it. If that holds, the loop cannot hitch, and no crossfade,
trim or blend is needed anywhere.

Runs without Blender: `loop.py`'s phase maths imports nothing from `bpy`.

    python3 blender/tests/test_loop.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from aero.loop import LoopClock  # noqa: E402

FAILURES: list[str] = []


def check(condition: bool, message: str) -> None:
    if condition:
        print(f"  ok   {message}")
    else:
        print(f"  FAIL {message}")
        FAILURES.append(message)


def approx(a: float, b: float, tolerance: float = 1e-12) -> bool:
    return abs(a - b) <= tolerance


CLOCKS = [LoopClock(frames=60, fps=30), LoopClock(frames=300, fps=30), LoopClock(frames=241, fps=24)]

print("the wrap lands exactly on the start")
for clock in CLOCKS:
    for cycles in (1, 2, 5):
        for offset in (0.0, 0.137, 0.5, 0.91):
            wrap = clock.phase(clock.frames + 1, cycles, offset)
            start = clock.phase(1, cycles, offset)
            if not approx(wrap, start):
                check(False, f"{clock.frames}f cycles={cycles} offset={offset}: {wrap} != {start}")
                continue
    check(True, f"{clock.frames} frames: phase returns exactly, every cycle count and offset")

print("sine closes too")
for clock in CLOCKS:
    worst = max(
        abs(clock.sine(clock.frames + 1, cycles, offset) - clock.sine(1, cycles, offset))
        for cycles in (1, 3)
        for offset in (0.0, 0.25, 0.6)
    )
    check(worst < 1e-12, f"{clock.frames} frames: sine wraps to within {worst:.1e}")

print("the last rendered frame is one step short, not a duplicate")
for clock in CLOCKS:
    # If frame N equalled frame 1, rendering both would show the same image
    # twice and the loop would visibly stutter once per cycle.
    gap = abs(clock.phase(clock.frames, cycles=1) - clock.phase(1, cycles=1))
    expected = (clock.frames - 1) / clock.frames
    check(approx(gap, expected), f"{clock.frames} frames: frame N sits {expected:.4f} into the cycle")

print("travel fades out at both ends")
check(approx(LoopClock.fade(0.0), 0.0), "fade is 0 where travel starts")
check(approx(LoopClock.fade(1.0), 0.0), "fade is 0 where travel ends")
check(approx(LoopClock.fade(0.5), 1.0), "fade is 1 through the middle")
check(LoopClock.fade(0.05) < LoopClock.fade(0.1), "fade rises monotonically into the run")
check(LoopClock.fade(0.9) > LoopClock.fade(0.95), "fade falls monotonically out of it")
check(approx(LoopClock.fade(0.5, edge=0.0), 1.0), "a zero edge means no fade at all")

print("a rise spreads its population evenly")
clock = LoopClock(frames=120)
# Two particles half a cycle apart must stay half a cycle apart all the way
# round, or the field bunches up and the reset becomes visible.
gaps = {round((clock.rise(f, offset=0.5) - clock.rise(f, offset=0.0)) % 1.0, 9) for f in range(1, 121)}
check(gaps == {0.5}, "phase offsets are preserved on every frame")

print("the integer-cycle rule is enforced")
for bad in (0, -1, 1.5, 0.5):
    try:
        LoopClock(frames=60).phase(1, cycles=bad)
    except ValueError:
        check(True, f"cycles={bad} is rejected")
    else:
        check(False, f"cycles={bad} was accepted and would break the loop")

print("seconds are reported honestly")
check(approx(LoopClock(frames=300, fps=30).seconds, 10.0), "300 frames at 30fps is 10 seconds")
check(approx(LoopClock(frames=240, fps=24).seconds, 10.0), "240 frames at 24fps is 10 seconds")

print()
if FAILURES:
    print(f"{len(FAILURES)} failed")
    raise SystemExit(1)
print("all passed")
